#!/bin/bash
echo "  正在配置PHP... "
sed -i -e 's/;extension=intl/extension=intl/i' /etc/php/7.4/fpm/php.ini
sed -i -e 's/;extension=intl/extension=intl/i' /etc/php/7.4/cli/php.ini
apt-get install php7.4-intl
service nginx restart
service php7.4-fpm restart
clear

echo "   正在配置composer...  "
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === '795f976fe0ebd8b75f26a6dd68f78fd3453ce79f32ecb33e7fd087d39bfeb978342fb73ac986cd4f54edd0dc902601dc') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
mv composer.phar /usr/local/bin/composer
clear

echo " 正在配置nginx組態... "
echo "
server { 
        root /var/www/web/public;
        index index.html index.php;

        # set expiration of assets to MAX for caching
        location ~* \.(ico|css|js|gif|jpe?g|png)(\?[0-9]+)?$ {
                expires max;
                log_not_found off;
        }

        location / {
                try_files \$uri \$uri/ /index.php;
        }

        location ~* \.php$ {
                fastcgi_pass unix:/run/php/php7.4-fpm.sock;
                include fastcgi.conf;
        }
}">nginx.conf;
######
cp nginx.conf /etc/nginx/sites-enabled/nginx.conf
nginx -t
service nginx restart
clear

echo " 正在安裝codeigniter4... "
cd /var/www
composer create-project codeigniter4/appstarter web
rm /etc/nginx/sites-enabled/default
cd /web
composer install
clear

echo " codeigniter4 安裝完畢 "