#!/bin/bash
service mysql stop
service nginx stop
service php7.4-fpm stop
service redis-server stop
#如果軟連結不存在則建立軟連結
echo "連結phpmyadmin"
ln -s /usr/share/phpmyadmin /var/www/public
echo "服務啟動狀態"
service --status-all